---
- name: Setup Docker Network and Volume
  hosts: all
  become: yes

  tasks:
    - name: Create Docker Network
      docker_network:
        name: ip2-app-net
        driver: bridge
        ipam_config:
          - subnet: 172.18.0.0/16
            ip_range: 172.18.0.0/16

    - name: Create Docker Volume for MongoDB
      docker_volume:
        name: ip2-mongo-data

