---
- name: Deploy IP3 Application using Ansible
  hosts: all
  become: yes

  roles:
    - role: network_volume
      tags: network

    - role: mongodb
      tags: mongodb

    - role: backend
      tags: backend

    - role: frontend
      tags: frontend

